name: Mobuild Envuscator
description: Build obfuscated mobile libraries from environment configuration
inputs:
  env:
    description: "Base64 encoded environment config"
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Build libraries
      id: envuscator
      uses: hackelia-micrantha/mobuild-envuscator/.github/actions/envuscator-build-all@main
      with:
        env: ${{ inputs.env }}

    - name: Update dependencies in project
      run: |
        cp -rf ${{ steps.envuscator.outputs.bin }}/Debug/android/mobuild-envuscator.aar composeApp/mobuild-envuscator-debug.aar
        cp -rf ${{ steps.envuscator.outputs.bin }}/Release/android/mobuild-envuscator.aar composeApp/mobuild-envuscator-release.aar
        cp -rf ${{ steps.envuscator.outputs.bin }}/Debug/ios/MobuildEnvuscator.xcframework iosApp/MobuildEnvuscator/Debug/
        cp -rf ${{ steps.envuscator.outputs.bin }}/Release/ios/MobuildEnvuscator.xcframework iosApp/MobuildEnvuscator/Release/
      shell: "bash"
