name: Mobuild Envuscator
description: Build obfuscated mobile libraries from environment configuration
inputs:
  config:
    description: "Base64 encoded environment config"
    required: true
    type: string
  token:
    description: "Access token for the envuscator repository"
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - id: config-hash
      run: echo "key=$(echo -n '${{ inputs.config }}' | shasum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Check for cached build
      uses: actions/cache/restore@v4
      id: build-cache
      with:
        path: ${{ github.workspace }}/.envuscator
        key: build-cache-${{ runner.os }}-${{ steps.config-hash.outputs.key }}

    - name: "Checkout actions"
      if: steps.build-cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: hackelia-micrantha/actions
        token: ${{ inputs.token }}
        ref: v1
        path: micrantha-actions

    - name: Build libraries
      if: steps.build-cache.outputs.cache-hit != 'true'
      id: envuscator
      uses: ./micrantha-actions/.github/actions/envuscator-build-all
      with:
        config: ${{ inputs.config }}
        token: ${{ inputs.token }}

    - name: Cache files
      if: steps.build-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/.envuscator
        key: build-cache-${{ runner.os }}-${{ steps.config-hash.outputs.key }}

    - name: Update project libraries
      run: |
        cp -rf "${{ github.workspace }}/.envuscator/Debug/android/mobuild-envuscator.aar" "composeApp/libs/debug/"
        cp -rf "${{ github.workspace }}/.envuscator/Release/android/mobuild-envuscator.aar" "composeApp/libs/release/"
        cp -rf "${{ github.workspace }}/.envuscator/Debug/ios/MobuildEnvuscator.xcframework" "iosApp/MobuildEnvuscator/debug/"
        cp -rf "${{ github.workspace }}/.envuscator/Release/ios/MobuildEnvuscator.xcframework" "iosApp/MobuildEnvuscator/release/"
      shell: bash
        