platform :ios, '15.0'

source 'https://cdn.cocoapods.org'

target 'iosApp' do
  use_frameworks!

  pod 'MediaPipeTasksVision'
  pod 'MediaPipeTasksGenAI'

  pod 'composeApp', :path => '../composeApp'
end
