
platform :ios do
  import('./Fastfile.ios')
end

platform :android do
  import('./Fastfile.android')
end

import('./Fastfile.supabase')

desc "Build Debug iOS and Android"
lane :build_debug do |options|
  Fastlane::LaneManager.cruise_lane("android", "build_debug", options)
  Fastlane::LaneManager.cruise_lane("ios", "build_debug", options)
end

desc "Build Release iOS and Android"
lane :build_release do |options|
  Fastlane::LaneManager.cruise_lane("android", "build_release", options)
  Fastlane::LaneManager.cruise_lane("ios", "build_release", options)
end

desc "Distribute iOS and Android to stores for testing"
lane :distribute do |options|
  Fastlane::LaneManager.cruise_lane("android", "distribute", options)
  Fastlane::LaneManager.cruise_lane("ios", "distribute", options)
end

desc "Run all unit tests"
lane :test do
  gradle(
    task: "test"
  )
end
