name: Production
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  supabase:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/supabase
        with:
          access_token: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          project_id: ${{ secrets.SUPABASE_PROJECT_ID }}
          db_password: ${{ secrets.SUPABASE_DB_URL }}

  mobile:
    runs-on: macos-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Create build config
        uses: ./.github/actions/configure-build
        id: build-config
        with:
          android_keystore: ${{ secrets.ANDROID_STORE_FILE }}
          login_email: ${{ inputs.login_email }}
          login_password: ${{ inputs.login_password }}

      - name: Build environment configuration
        uses: ./.github/actions/mobuild-envuscator
        with:
          config: ${{ secrets.APP_CONFIG }}
          token: ${{ secrets.ENVUSCATOR_PAT }}

      - uses: maierj/fastlane-action@v3.1.0
        with:
          lane: "distribute_production"
        env:
          APPLE_CONNECT_ID: "${{ secrets.APPLE_CONNECT_ID }}"
          APPLE_TEAM_ID: "${{ secrets.APPLE_TEAM_ID }}"
          APPLE_USERNAME: "${{ secrets.APPLE_USERNAME }}"
          ANDROID_STORE_FILE: "${{ steps.build-config.outputs.android_keystore }}"
          ANDROID_STORE_PASSWORD: "${{ secrets.ANDROID_STORE_PASSWORD }}"
          ANDROID_KEY_ALIAS: "${{ secrets.ANDROID_KEY_ALIAS }}"
          ANDROID_KEY_PASSWORD: "${{ secrets.ANDROID_KEY_PASSWORD }}"
